import type { Metadata } from 'next';
import '@/assets/scss/style.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body>{children}</body>
        </html>
    );
}
